[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "targets/acorn_amd64.json"
target-dir = "../build/artf/kernel"

[target.acorn_amd64]
rustflags = [
	"-C", "link-arg=-Tamd64.ld",
	"-C", "force-frame-pointers",
	"-C", "force-unwind-tables",
]