[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "macros",
    "macros/defs",
]

[dependencies]
cfg-if = "1.0.0"
log = "0.4.17"
spin = "0.9.4"
static_assertions = "1.1.0"
proc-macro = {path = "macros"}


