[workspace]
members = [
    "boot",
    "kernel",
    "mm",
    "util",
    
    "arch/*",

    "lib/*",
]

[profile.dev]
opt-level = 1
debug-assertions = true 
debug = true
lto = false

[profile.release]
opt-level = 3
lto = true