[workspace]
members = [
    "arch",
    "boot",
    "kernel",
    "mm",
]

[profile.dev]
opt-level = 0
debug-assertions = true 
debug = true
lto = false
panic = "abort"

[profile.release]
opt-level = 3
lto = true
panic = "abort"