[toolchain]
channel = "nightly-2023-04-13"
components = [ "rustfmt", "rustc-dev", "llvm-tools-preview", "rust-analysis", "rust-src", "clippy", "rust-analyzer", "rustc", "cargo", "rust-docs" ]
profile = "minimal"