[package]
name = "amd64"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1.0.0"
spin = "0.9.4"
static_assertions = "1.1.0"

[dependencies.hal]
path = "../../hal"

[dependencies.util]
path = "../../util"

[dependencies.proc-macro]
path = "../../macros"
