[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kernel"
path = "src/main.rs"

[lib]
name = "klib"
path = "klib/lib.rs"

[dependencies]
cfg-if = "1.0.0"
static_assertions = "1.1.0"
spin = "0.9.5"
log = "0.4.17"
proc-bitfield = "0.2.2"

[dependencies.ctor]
path = "lib/ctor"

[dependencies.bitmap]
path = "lib/bitmap"

[members]
members = [
    "lib/ctor",
    "lib/bitmap",
]