[package]
name = "mm"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1.0.0"
static_assertions = "1.1.0"

[dependencies.libmm]
path = "../lib/libmm"

[dependencies.util]
path = "../util"

